# Generated by Django 5.0.4 on 2024-05-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('roll', models.CharField(max_length=55, null=True, unique=True)),
                ('city', models.CharField(max_length=55)),
                ('marks', models.IntegerField()),
                ('join_Date', models.DateField()),
            ],
        ),
    ]
